### ISSUE TITLE
Hi Aloke

### ISSUE THREAD

**Issue by zsherman** [zsherman/watson#69]

**Comment by ajwaxman** [comment]
Stop showing off watson :wink:

**Comment by zsherman** [comment]
Hahahaha

**Comment by zsherman** [comment]
FUUUCK https://www.dropbox.com/s/kibbybgg6sqbz5n/Screenshot%202015-01-31%2014.04.57.png?dl=0

**Comment by ajwaxman** [comment]
Haha I actually got it working

**Comment by ajwaxman** [comment]
Had to install bower globally, which wouldn't work until i changed some permissions

**Comment by zsherman** [comment]
Got it.
